fibon: fibon.o functions.o
	gcc -g -ansi -Wall -pedantic fibon.o functions.o -o fibon

fibon.o: fibon.c data.h
	gcc -c -ansi -Wall -pedantic fibon.c -o fibon.o

functions.o: functions.c data.h
	gcc -c -ansi -Wall -pedantic functions.c -o functions.o
